# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cansu/project_32768/project_32768.srcs/sources_1/bd/Top/ip/Top_s00_mmu_0/Top_s00_mmu_0.xci
# IP: The module: 'Top_s00_mmu_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cansu/project_32768/project_32768.gen/sources_1/bd/Top/ip/Top_s00_mmu_0/Top_s00_mmu_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_s00_mmu_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/cansu/project_32768/project_32768.srcs/sources_1/bd/Top/ip/Top_s00_mmu_0/Top_s00_mmu_0.xci
# IP: The module: 'Top_s00_mmu_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cansu/project_32768/project_32768.gen/sources_1/bd/Top/ip/Top_s00_mmu_0/Top_s00_mmu_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_s00_mmu_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
