#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jan 14 23:15:58 CET 2026
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_multi_cores_top_behav -key {Behavioral:sim_1:Functional:tb_multi_cores_top} -tclbatch tb_multi_cores_top.tcl -protoinst "protoinst_files/Top.protoinst" -view /home/cansu/project_32768/project_32768.srcs/sim_1/imports/project_13/multi_cores_top_tb_behav.wcfg -log simulate.log"
xsim tb_multi_cores_top_behav -key {Behavioral:sim_1:Functional:tb_multi_cores_top} -tclbatch tb_multi_cores_top.tcl -protoinst "protoinst_files/Top.protoinst" -view /home/cansu/project_32768/project_32768.srcs/sim_1/imports/project_13/multi_cores_top_tb_behav.wcfg -log simulate.log

