# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/early.xdc

# XDC: imports/constraints/normal.xdc

# Block Designs: bd/Top/Top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top || ORIG_REF_NAME==Top} -quiet] -quiet

# IP: bd/Top/ip/Top_xlconstant_1_0_1/Top_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xlconstant_1_0 || ORIG_REF_NAME==Top_xlconstant_1_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_interconnect_1_1/Top_axi_interconnect_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_interconnect_1_1 || ORIG_REF_NAME==Top_axi_interconnect_1_1} -quiet] -quiet

# IP: bd/Top/ip/Top_util_ds_buf_0_1/Top_util_ds_buf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_util_ds_buf_0 || ORIG_REF_NAME==Top_util_ds_buf_0} -quiet] -quiet

# IP: bd/Top/ip/Top_xdma_0_0_1/Top_xdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xdma_0_0 || ORIG_REF_NAME==Top_xdma_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_xbar_1/Top_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xbar_1 || ORIG_REF_NAME==Top_xbar_1} -quiet] -quiet

# IP: bd/Top/ip/Top_xdma_0_axi_periph_0/Top_xdma_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xdma_0_axi_periph_0 || ORIG_REF_NAME==Top_xdma_0_axi_periph_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_bram_ctrl_0_0/Top_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Top_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_blk_mem_gen_0_1/Top_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_blk_mem_gen_0_1 || ORIG_REF_NAME==Top_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_gpio_0_0/Top_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_gpio_0_0 || ORIG_REF_NAME==Top_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_gpio_1_0/Top_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_gpio_1_0 || ORIG_REF_NAME==Top_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Top/ip/Top_rst_clk_wiz_100M_0/Top_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_rst_clk_wiz_100M_0 || ORIG_REF_NAME==Top_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/Top/ip/Top_clk_wiz_1/Top_clk_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_clk_wiz_1 || ORIG_REF_NAME==Top_clk_wiz_1} -quiet] -quiet

# IP: bd/Top/ip/Top_util_vector_logic_0_0/Top_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_util_vector_logic_0_0 || ORIG_REF_NAME==Top_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_gpio_2_0/Top_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_gpio_2_0 || ORIG_REF_NAME==Top_axi_gpio_2_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_gpio_3_0/Top_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_gpio_3_0 || ORIG_REF_NAME==Top_axi_gpio_3_0} -quiet] -quiet

# IP: bd/Top/ip/Top_xlconstant_0_0/Top_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_xlconstant_0_0 || ORIG_REF_NAME==Top_xlconstant_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_axi_gpio_3_1/Top_axi_gpio_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_axi_gpio_3_1 || ORIG_REF_NAME==Top_axi_gpio_3_1} -quiet] -quiet

# IP: bd/Top/ip/Top_comparator_0_0/Top_comparator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_comparator_0_0 || ORIG_REF_NAME==Top_comparator_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_multi_cores_top_0_0/Top_multi_cores_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_multi_cores_top_0_0 || ORIG_REF_NAME==Top_multi_cores_top_0_0} -quiet] -quiet

# IP: bd/Top/ip/Top_auto_cc_0/Top_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_auto_cc_0 || ORIG_REF_NAME==Top_auto_cc_0} -quiet] -quiet

# IP: bd/Top/ip/Top_auto_cc_1/Top_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Top_auto_cc_1 || ORIG_REF_NAME==Top_auto_cc_1} -quiet] -quiet

# XDC: /home/cansu/Desktop/bf2/bf2_hw/bf2_hw.gen/sources_1/bd/Top/Top_ooc.xdc
