#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Script generated by Vivado on Wed Sep 23 17:01:20 CEST 2026
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# Tool Version Limit: 2023.05 
#
# Filename     : Top.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : Top.sh
#                Top.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                Top.sh [-reset_run]
#                Top.sh [-reset_log]
#                Top.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the Xilinx simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'Top.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -relax -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname xlconstant_v1_1_7 -libname xil_defaultlib -libname blk_mem_gen_v8_4_6 -libname fifo_generator_v13_1_4 -libname xdma_v4_1_23 -libname generic_baseblocks_v2_1_0 -libname axi_infrastructure_v1_1_0 -libname axi_register_slice_v2_1_28 -libname fifo_generator_v13_2_8 -libname axi_data_fifo_v2_1_27 -libname axi_crossbar_v2_1_29 -libname axi_bram_ctrl_v4_1_8 -libname axi_lite_ipif_v3_0_4 -libname lib_cdc_v1_0_2 -libname interrupt_control_v3_1_4 -libname axi_gpio_v2_0_30 -libname proc_sys_reset_v5_0_13 -libname util_vector_logic_v2_0_2 -libname axi_clock_converter_v2_1_27 -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm xlconstant_v1_1_7 xil_defaultlib blk_mem_gen_v8_4_6 fifo_generator_v13_1_4 xdma_v4_1_23 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_28 fifo_generator_v13_2_8 axi_data_fifo_v2_1_27 axi_crossbar_v2_1_29 axi_bram_ctrl_v4_1_8 axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_30 proc_sys_reset_v5_0_13 util_vector_logic_v2_0_2 axi_clock_converter_v2_1_27)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "Top.sh - Script generated by export_simulation (Vivado v2023.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./Top.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "/tools/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm -V93 $xmvhdl_opts \
  "/tools/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work xlconstant_v1_1_7 $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/b0f2/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/Top/ip/Top_xlconstant_1_0_1/sim/Top_xlconstant_1_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/Top/ip/Top_util_ds_buf_0_1/util_ds_buf.vhd" \
  "../../../bd/Top/ip/Top_util_ds_buf_0_1/sim/Top_util_ds_buf_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pipe_clock.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pipe_eq.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pipe_drp.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pipe_rate.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pipe_reset.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pipe_sync.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_gtp_pipe_rate.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_gtp_pipe_drp.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_gtp_pipe_reset.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pipe_user.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pipe_wrapper.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_qpll_drp.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_qpll_reset.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_qpll_wrapper.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_rxeq_scan.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pcie_top.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_core_top.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_axi_basic_rx_null_gen.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_axi_basic_rx_pipeline.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_axi_basic_rx.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_axi_basic_top.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_axi_basic_tx_pipeline.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_axi_basic_tx_thrtl_ctl.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_axi_basic_tx.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pcie_7x.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pcie_bram_7x.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pcie_bram_top_7x.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pcie_brams_7x.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pcie_pipe_lane.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pcie_pipe_misc.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pcie_pipe_pipeline.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_gt_top.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_gt_common.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_gtp_cpllpd_ovrd.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_gtx_cpllpd_ovrd.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_gt_rx_valid_filter_7x.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_gt_wrapper.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/source/Top_xdma_0_0_pcie2_ip_pcie2_top.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_0/sim/Top_xdma_0_0_pcie2_ip.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_6 $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/bb55/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_1/sim/xdma_v4_1_23_blk_mem_64_reg_be.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_2/sim/xdma_v4_1_23_blk_mem_64_noreg_be.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work fifo_generator_v13_1_4 $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/e6d5/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_1_4 -V93 $xmvhdl_opts \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/e6d5/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_1_4 $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/e6d5/hdl/fifo_generator_v13_1_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_3/sim/pcie2_fifo_generator_dma_cpl.v" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/ip_4/sim/pcie2_fifo_generator_tgt_brdg.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xdma_v4_1_23 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/xdma_v4_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/xdma_v4_1/hdl/verilog/Top_xdma_0_0_dma_cpl.sv" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/xdma_v4_1/hdl/verilog/Top_xdma_0_0_dma_req.sv" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/xdma_v4_1/hdl/verilog/Top_xdma_0_0_rx_destraddler.sv" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/xdma_v4_1/hdl/verilog/Top_xdma_0_0_rx_demux.sv" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/xdma_v4_1/hdl/verilog/Top_xdma_0_0_tgt_cpl.sv" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/xdma_v4_1/hdl/verilog/Top_xdma_0_0_tgt_req.sv" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/xdma_v4_1/hdl/verilog/Top_xdma_0_0_tx_mux.sv" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/xdma_v4_1/hdl/verilog/Top_xdma_0_0_axi_stream_intf.sv" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/xdma_v4_1/hdl/verilog/Top_xdma_0_0_cfg_sideband.sv" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/xdma_v4_1/hdl/verilog/Top_xdma_0_0_pcie2_to_pcie3_wrapper.sv" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/xdma_v4_1/hdl/verilog/Top_xdma_0_0_dma_bram_wrap.sv" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/xdma_v4_1/hdl/verilog/Top_xdma_0_0_dma_bram_wrap_1024.sv" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/xdma_v4_1/hdl/verilog/Top_xdma_0_0_dma_bram_wrap_2048.sv" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/xdma_v4_1/hdl/verilog/Top_xdma_0_0_core_top.sv" \
  "../../../bd/Top/ip/Top_xdma_0_0_1/sim/Top_xdma_0_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work generic_baseblocks_v2_1_0 $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_28 $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/87d1/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_8 $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/c97d/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_8 -V93 $xmvhdl_opts \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_8 $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_data_fifo_v2_1_27 $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/fab7/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_crossbar_v2_1_29 $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/f8f3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/Top/ip/Top_xbar_1/sim/Top_xbar_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_bram_ctrl_v4_1_8 -V93 $xmvhdl_opts \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/85f5/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/Top/ip/Top_axi_bram_ctrl_0_0/sim/Top_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/Top/ip/Top_blk_mem_gen_0_1/sim/Top_blk_mem_gen_0_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 -V93 $xmvhdl_opts \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_2 -V93 $xmvhdl_opts \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work interrupt_control_v3_1_4 -V93 $xmvhdl_opts \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_gpio_v2_0_30 -V93 $xmvhdl_opts \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/18b7/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/Top/ip/Top_axi_gpio_0_0/sim/Top_axi_gpio_0_0.vhd" \
  "../../../bd/Top/ip/Top_axi_gpio_1_0/sim/Top_axi_gpio_1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_13 -V93 $xmvhdl_opts \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/Top/ip/Top_rst_clk_wiz_100M_0/sim/Top_rst_clk_wiz_100M_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/Top/ip/Top_clk_wiz_1/Top_clk_wiz_1_clk_wiz.v" \
  "../../../bd/Top/ip/Top_clk_wiz_1/Top_clk_wiz_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work util_vector_logic_v2_0_2 $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/3d84/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/Top/ip/Top_util_vector_logic_0_0/sim/Top_util_vector_logic_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/Top/ip/Top_axi_gpio_2_0/sim/Top_axi_gpio_2_0.vhd" \
  "../../../bd/Top/ip/Top_axi_gpio_3_0/sim/Top_axi_gpio_3_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/Top/ip/Top_xlconstant_0_0/sim/Top_xlconstant_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/Top/ip/Top_axi_gpio_3_1/sim/Top_axi_gpio_3_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/Top/ip/Top_comparator_0_0/sim/Top_comparator_0_0.v" \
  "../../../bd/Top/ip/Top_multi_cores_top_0_0/sim/Top_multi_cores_top_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_clock_converter_v2_1_27 $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/29db/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/03b2/hdl/verilog" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/ec67/hdl" +incdir+"../../../../bf2_hw.gen/sources_1/bd/Top/ipshared/30ef" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/Top/ip/Top_auto_cc_0/sim/Top_auto_cc_0.v" \
  "../../../bd/Top/ip/Top_auto_cc_1/sim/Top_auto_cc_1.v" \
  "../../../bd/Top/sim/Top.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.Top xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.Top -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/cansu/Desktop/bf2/bf2_hw/bf2_hw.cache/compile_simlib/xcelium"
  fi

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log Top_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./Top.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: Top.sh [-help]\n\
Usage: Top.sh [-step]\n\
Usage: Top.sh [-lib_map_path]\n\
Usage: Top.sh [-reset_run]\n\
Usage: Top.sh [-reset_log]\n\
Usage: Top.sh [-keep_index]\n\
Usage: Top.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
