# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cansu/bf2_hw/bf2_hw.srcs/sources_1/bd/Top/ip/Top_axi_bram_ctrl_0_0/Top_axi_bram_ctrl_0_0.xci
# IP: The module: 'Top_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cansu/bf2_hw/bf2_hw.gen/sources_1/bd/Top/ip/Top_axi_bram_ctrl_0_0/Top_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/cansu/bf2_hw/bf2_hw.srcs/sources_1/bd/Top/ip/Top_axi_bram_ctrl_0_0/Top_axi_bram_ctrl_0_0.xci
# IP: The module: 'Top_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cansu/bf2_hw/bf2_hw.gen/sources_1/bd/Top/ip/Top_axi_bram_ctrl_0_0/Top_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
