# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cansu/project_4096/project_4096.srcs/sources_1/bd/Top/ip/Top_rst_clk_wiz_100M_0/Top_rst_clk_wiz_100M_0.xci
# IP: The module: 'Top_rst_clk_wiz_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cansu/project_4096/project_4096.gen/sources_1/bd/Top/ip/Top_rst_clk_wiz_100M_0/Top_rst_clk_wiz_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/cansu/project_4096/project_4096.gen/sources_1/bd/Top/ip/Top_rst_clk_wiz_100M_0/Top_rst_clk_wiz_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/cansu/project_4096/project_4096.gen/sources_1/bd/Top/ip/Top_rst_clk_wiz_100M_0/Top_rst_clk_wiz_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/cansu/project_4096/project_4096.srcs/sources_1/bd/Top/ip/Top_rst_clk_wiz_100M_0/Top_rst_clk_wiz_100M_0.xci
# IP: The module: 'Top_rst_clk_wiz_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cansu/project_4096/project_4096.gen/sources_1/bd/Top/ip/Top_rst_clk_wiz_100M_0/Top_rst_clk_wiz_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/cansu/project_4096/project_4096.gen/sources_1/bd/Top/ip/Top_rst_clk_wiz_100M_0/Top_rst_clk_wiz_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/cansu/project_4096/project_4096.gen/sources_1/bd/Top/ip/Top_rst_clk_wiz_100M_0/Top_rst_clk_wiz_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_rst_clk_wiz_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
