# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cansu/4096_bf_trytests/4096_bf_trytests.srcs/sources_1/bd/Top/ip/Top_axi_gpio_3_1/Top_axi_gpio_3_1.xci
# IP: The module: 'Top_axi_gpio_3_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cansu/4096_bf_trytests/4096_bf_trytests.gen/sources_1/bd/Top/ip/Top_axi_gpio_3_1/Top_axi_gpio_3_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/cansu/4096_bf_trytests/4096_bf_trytests.gen/sources_1/bd/Top/ip/Top_axi_gpio_3_1/Top_axi_gpio_3_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/cansu/4096_bf_trytests/4096_bf_trytests.gen/sources_1/bd/Top/ip/Top_axi_gpio_3_1/Top_axi_gpio_3_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/cansu/4096_bf_trytests/4096_bf_trytests.srcs/sources_1/bd/Top/ip/Top_axi_gpio_3_1/Top_axi_gpio_3_1.xci
# IP: The module: 'Top_axi_gpio_3_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cansu/4096_bf_trytests/4096_bf_trytests.gen/sources_1/bd/Top/ip/Top_axi_gpio_3_1/Top_axi_gpio_3_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/cansu/4096_bf_trytests/4096_bf_trytests.gen/sources_1/bd/Top/ip/Top_axi_gpio_3_1/Top_axi_gpio_3_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/cansu/4096_bf_trytests/4096_bf_trytests.gen/sources_1/bd/Top/ip/Top_axi_gpio_3_1/Top_axi_gpio_3_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
