# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cansu/4096_bf_trytests/4096_bf_trytests.srcs/sources_1/bd/Top/ip/Top_util_ds_buf_0_1/Top_util_ds_buf_0.xci
# IP: The module: 'Top_util_ds_buf_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cansu/4096_bf_trytests/4096_bf_trytests.gen/sources_1/bd/Top/ip/Top_util_ds_buf_0_1/Top_util_ds_buf_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_util_ds_buf_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/cansu/4096_bf_trytests/4096_bf_trytests.gen/sources_1/bd/Top/ip/Top_util_ds_buf_0_1/Top_util_ds_buf_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_util_ds_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/cansu/4096_bf_trytests/4096_bf_trytests.srcs/sources_1/bd/Top/ip/Top_util_ds_buf_0_1/Top_util_ds_buf_0.xci
# IP: The module: 'Top_util_ds_buf_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cansu/4096_bf_trytests/4096_bf_trytests.gen/sources_1/bd/Top/ip/Top_util_ds_buf_0_1/Top_util_ds_buf_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_util_ds_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/cansu/4096_bf_trytests/4096_bf_trytests.gen/sources_1/bd/Top/ip/Top_util_ds_buf_0_1/Top_util_ds_buf_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Top_util_ds_buf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
